### PR TITLE
Fall mis-representation fix

### PR DESCRIPTION
**Pull request by forteddyt**
Previously, the Fall semester was represented as an 8.
This changes it from an 8 representation to a 9.
Here's my evidence on why it's now represented as an 8, not a 9: http://i.imgur.com/rGWrIoH.png

### CODE REVIEW

**Comment by kevincianfarini** [comment]
Do all of the tests still pass with this change? I still need to get the CI properly set up to work with this fork since it's no longer just my personal project.

**Comment by forteddyt** [comment]
I'm not near my computer atm, and I haven't tested it myself. I approved your Travis CI access, though.

**Comment by forteddyt** [comment]
How do I test local changes, exactly?

**Comment by kevincianfarini** [comment]
If you'd like to run the tests locally, this will help you achieve that the same way as the CI process does. https://github.com/VirginiaTech/pyvt/blob/master/.travis.yml#L7 I just got the CI up and running for this repo, so when you've ironed out any bugs that may have changed because of this (I'm expecting some in the cached HTML file the tests are being run against) update your PR and the CI should verify that we're good to go.

**Comment by kevincianfarini** [comment]
really sorry for the hastle, but I don't think travis CI picked up the PR since it existed before travis was active on this repo. Would you mind closing this and reopening a PR for me?

**Comment by forteddyt** [comment]
Not a problem, I'll do that now

**Pull request closed without merging**
